ALTER TABLE `artworks` ADD `external_image_url` text;
--> statement-breakpoint
INSERT INTO `artists` (`name`, `slug`, `biography`, `created_at`, `updated_at`) VALUES
  ('Mara Voss', 'mara-voss', 'A painter whose work studies memory, atmosphere, and place.', unixepoch(), unixepoch()),
  ('Theo Laurent', 'theo-laurent', 'An interdisciplinary artist working across painting and drawing.', unixepoch(), unixepoch()),
  ('Inez Calder', 'inez-calder', 'A mixed-media artist interested in weather, movement, and landscape.', unixepoch(), unixepoch()),
  ('Sora Bennett', 'sora-bennett', 'An artist exploring light and architectural rhythm on paper.', unixepoch(), unixepoch());
--> statement-breakpoint
INSERT INTO `artworks` (`accession_number`, `slug`, `artist_id`, `title`, `year`, `medium`, `width_in`, `height_in`, `description`, `provenance`, `price_cents`, `currency`, `status`, `external_image_url`, `published`, `created_at`, `updated_at`) VALUES
  ('AA-001', 'the-quiet-between', (SELECT `id` FROM `artists` WHERE `slug` = 'mara-voss'), 'The Quiet Between', 2024, 'Oil on linen', 36, 48, 'From the artist''s ongoing study of memory and place, this work layers gestural marks with quieter passages of color.', 'Signed and dated verso. Certificate of authenticity included.', 480000, 'USD', 'available', 'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=1400&q=85', 1, unixepoch(), unixepoch()),
  ('AA-002', 'field-notes-no-7', (SELECT `id` FROM `artists` WHERE `slug` = 'theo-laurent'), 'Field Notes No. 7', 2023, 'Acrylic on canvas', 40, 40, 'A layered record of color, gesture, and observation.', 'Signed and dated verso. Certificate of authenticity included.', 320000, 'USD', 'reserved', 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=1400&q=85', 1, unixepoch(), unixepoch()),
  ('AA-003', 'after-the-rain', (SELECT `id` FROM `artists` WHERE `slug` = 'inez-calder'), 'After the Rain', 2024, 'Mixed media', 30, 42, 'A study of shifting weather and the softened edges of the landscape.', 'Signed and dated verso. Certificate of authenticity included.', 390000, 'USD', 'available', 'https://images.unsplash.com/photo-1646782013671-66599767f714?auto=format&fit=crop&w=1400&q=85', 1, unixepoch(), unixepoch()),
  ('AA-004', 'blue-hour', (SELECT `id` FROM `artists` WHERE `slug` = 'mara-voss'), 'Blue Hour', 2022, 'Oil on panel', 24, 30, 'A quiet study of the light between day and night.', 'Signed and dated verso. Certificate of authenticity included.', 290000, 'USD', 'sold', 'https://images.unsplash.com/photo-1676200832719-35b267832b04?auto=format&fit=crop&w=1400&q=85', 1, unixepoch(), unixepoch()),
  ('AA-005', 'folding-light', (SELECT `id` FROM `artists` WHERE `slug` = 'sora-bennett'), 'Folding Light', 2023, 'Pigment on paper', 22, 30, 'Pigment and negative space turn light into an architectural material.', 'Signed and dated verso. Certificate of authenticity included.', 185000, 'USD', 'available', 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=1400&q=85', 1, unixepoch(), unixepoch()),
  ('AA-006', 'soft-architecture', (SELECT `id` FROM `artists` WHERE `slug` = 'theo-laurent'), 'Soft Architecture', 2021, 'Acrylic and graphite', 48, 60, 'A large-scale work balancing structural marks with translucent fields.', 'Signed and dated verso. Certificate of authenticity included.', 560000, 'USD', 'available', 'https://images.unsplash.com/photo-1578301978018-3005759f48f7?auto=format&fit=crop&w=1400&q=85', 1, unixepoch(), unixepoch());
